Repository RamonSantos10/avaliacao2-tp2-stockapp, pull requests merged in 2025-06, with the labels that each got.

#140 feat: implementar sistema de feedback com análise de sentimento
  StockApp.API/Controllers/FeedbackController.cs
  StockApp.API/Program.cs
  StockApp.API/StockApp.API.csproj
  StockApp.API/appsettings.json
  StockApp.Application/Services/FeedbackService.cs
  StockApp.Application/Services/SentimentAnalysisService.cs
  StockApp.Domain.Test/FeedbackServicesTests.cs
  StockApp.Domain.Test/StockApp.Domain.Test.csproj
  StockApp.Domain/Entities/Feedback.cs
  StockApp.Domain/Interfaces/IFeedbackRepository.cs
  StockApp.Domain/Interfaces/IFeedbackService.cs
  StockApp.Domain/Interfaces/ISentimentAnalysisService.cs
  StockApp.Domain/StockApp.Domain.csproj
  StockApp.Infra.Data/Context/ApplicationDbContext.cs
  StockApp.Infra.Data/Repositories/FeedbackRepository.cs
  StockApp.Infra.Data/Repositories/InMemoryFeedbackRepository.cs
  StockApp.Infra.Data/StockApp.Infra.Data.csproj
  StockApp.Infra.IoC/DependencyInjection.cs
Labels: task, TP2

#138 Implementar sistema de alertas personalizados
  StockApp.API/Controllers/AlertsController.cs
  StockApp.API/appsettings.json
  StockApp.Application/Interfaces/IAlertService.cs
  StockApp.Application/Services/AlertService.cs
  StockApp.Application/StockApp.Application.csproj
  StockApp.Domain.Test/Services/AlertServicesTests.cs
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
Labels: task, TP2

#143 feat: adiciona paginação no endpoint GET de produtos
  StockApp.API/Controllers/ProductController.cs
  StockApp.API/Program.cs
  StockApp.Application/Interfaces/IProductService.cs
  StockApp.Application/Services/ProductService.cs
  StockApp.Domain.Test/ProductServiceTests.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
Labels: task, TP2

#144 feat: implementar endpoint e testes para relatório de estoque baixo
  StockApp.API/Controllers/ProductController.cs
  StockApp.Application/Interfaces/IProductService.cs
  StockApp.Application/Services/ProductService.cs
  StockApp.Domain.Test/Services/ProductServiceTests.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
Labels: task, TP2

#145 feat: implementar exportação de relatório de produtos em CSV com test…
  StockApp.API/Controllers/ProductController.cs
  StockApp.Domain.Test/ProductControllerTests.cs
  StockApp.Domain.Test/StockApp.Domain.Test.csproj
Labels: task, TP2

#149 Adicionado testes de integração para verificar o fluxo completo de re…
  StockApp.API/Controllers/TokenController.cs
  StockApp.API/Controllers/UsersController.cs
  StockApp.API/Program.cs
  StockApp.API/StockApp.API.csproj
  StockApp.Application/DTOs/AuthDTOs.cs
  StockApp.Application/Interfaces/IAuthService.cs
  StockApp.Application/Services/AuthService.cs
  StockApp.Domain.Test/IntegrationTests.cs
  StockApp.Domain.Test/StockApp.Domain.Test.csproj
  StockApp.Domain/Entities/User.cs
  StockApp.Domain/Interfaces/IUserRepository.cs
  StockApp.Infra.Data/Repositories/UserRepository.cs
Labels: enhancement

#150 Adicionado Funcionalidade de Upload de Imagem de Produtos
  StockApp.API/Controllers/ProductController.cs
  StockApp.API/Program.cs
  StockApp.API/wwwroot/images/2.jpg
Labels: enhancement

#152 Adicionado uma funcionalidade para repor automaticamente o estoque
  StockApp.API/Controllers/InventoryController.cs
  StockApp.Application/Interfaces/IInventoryService.cs
  StockApp.Application/Services/InventoryService.cs
  StockApp.Domain.Test/Services/InventoryServiceTests.cs
  StockApp.Domain.Test/StockApp.Domain.Test.csproj
  StockApp.Infra.IoC/DependencyInjection.cs
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
Labels: enhancement

#153 Adicionado Testes Unitários para o Controlador TokenController
  StockApp.API/Controllers/TokenController.cs
  StockApp.Domain.Test/TokenControllerTests.cs
Labels: enhancement

#154 Adicionado serviço de relatórios personalizados com relatórios de ven…
  CUSTOM_REPORTS_README.md
  StockApp.API/Controllers/CustomReportsController.cs
  StockApp.API/Program.cs
  StockApp.Application/DTOs/ReportDTO.cs
  StockApp.Application/Interfaces/ICustomReportService.cs
  StockApp.Application/Services/CustomReportService.cs
  StockApp.Domain.Test/CustomReportServiceTests.cs
Labels: enhancement

#156 Api externa para cotacao de precos
  StockApp.API/Controllers/PricingController.cs
  StockApp.API/Program.cs
  StockApp.Application/DTOs/ProductPricingDTO.cs
  StockApp.Application/Interfaces/IPricingService.cs
  StockApp.Application/Services/PricingService.cs
  StockApp.Application/StockApp.Application.csproj
  StockApp.Domain.Test/PricingServiceTests.cs
Labels: enhancement

#157 feat(products): add async product update with validation
  StockApp.API/Controllers/ProductsController.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
Labels: enhancement, TP2

#159 4. (13 pontos) Implementação dos Endpoints de Deleção (Delete) e Configuração no Program.cs
  StockApp.API/Controllers/ProductsController.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
Labels: enhancement, TP2

#160 Autenticação jwt no program
  StockApp.API/Program.cs
  StockApp.API/StockApp.API.csproj
  StockApp.API/appsettings.json
Labels: enhancement

#162 24. (5 pontos) Adicionar Logging usando Serilog
  StockApp.API/Program.cs
  StockApp.API/StockApp.API.csproj
Labels: enhancement, TP2

#164 27. (13 pontos) Implementar Endpoint de Atualização em Massa
  StockApp.API/Program.cs
  StockApp.API/StockApp.API.csproj
  StockApp.API/appsettings.json
Labels: enhancement, TP2
