Repository RamonSantos10/avaliacao2-tp2-stockapp, pull requests merged in 2025-07, with the labels that each got.

#165 54. (13 pontos) Adicionar Funcionalidade de Webhook
  StockApp.API/Controllers/WebhookController.cs
  StockApp.Application/DTOs/WebhookDto.cs
  StockApp.Application/Interfaces/IWebhookService.cs
  StockApp.Application/Services/WebhookService.cs
  StockApp.Infra.IoC/DependencyInjection.cs
Labels: enhancement, TP2

#166 Feat/sms feedback
  StockApp.API/Controllers/SmsFeedbackController.cs
  StockApp.API/Program.cs
  StockApp.API/appsettings.Development.json
  StockApp.API/appsettings.json
  StockApp.Application/Interfaces/ISmsFeedbackService.cs
  StockApp.Application/Services/FakeSmsService.cs
  StockApp.Application/Services/FeedbackService.cs
  StockApp.Application/Services/SmsFeedbackService.cs
  StockApp.Domain.Test/FeedbackServicesTests.cs
  StockApp.Domain.Test/SmsFeedbackServiceTests.cs
  StockApp.Domain/Interfaces/ISmsService.cs
  StockApp.Infra.Data/Context/ApplicationDbContext.cs
  StockApp.Infra.Data/Context/ApplicationDbContextFactory.cs
  StockApp.Infra.Data/Migrations/20250630023041_CreateFeedbackTable.Designer.cs
  StockApp.Infra.Data/Migrations/20250630023041_CreateFeedbackTable.cs
  StockApp.Infra.Data/Migrations/20250630140308_RecreateFeedbacks.Designer.cs
  StockApp.Infra.Data/Migrations/20250630140308_RecreateFeedbacks.cs
  StockApp.Infra.Data/Repositories/FeedbackRepository.cs
  StockApp.Infra.Data/Repositories/InMemoryFeedbackRepository.cs
  StockApp.Infra.Data/StockApp.Infra.Data.csproj
  StockApp.Infra.Data/log.txt
  StockApp.Infra.IoC/DependencyInjection.cs
Labels: task, TP2

#171 fix: corrigir inclusão e configuração do arquivo .env
  StockApp.API/Program.cs
  StockApp.API/StockApp.API.csproj
  StockApp.API/appsettings.json
  StockApp.Domain/StockApp.Domain.csproj
  StockApp.Infra.Data/Context/ApplicationDbContextFactory.cs
  StockApp.Infra.Data/StockApp.Infra.Data.csproj
Labels: bug

#173 27. (13 pontos) Implementar Endpoint de Atualização em Massa
  StockApp.API/Controllers/ProductsController.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
Labels: enhancement, TP2
